// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEvents)
}

func TestSoftDelete(t *testing.T) {}

func TestQuerySoftDeleteAll(t *testing.T) {}

func TestSliceSoftDeleteAll(t *testing.T) {}

func TestDelete(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsExists)
}

func TestFind(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsFind)
}

func TestBind(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsBind)
}

func TestOne(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsOne)
}

func TestAll(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsAll)
}

func TestCount(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsCount)
}

func TestHooks(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsInsert)
	t.Run("CalendarEvents", testCalendarEventsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("CalendarEvents", testCalendarEventsSliceUpdateAll)
}
